services:
  db: 
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mydb
    ports:
      - 5434:5432
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:
